apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-hello
  name: node-hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-hello
  type: LoadBalancer
status:
  loadBalancer: {}
